#!/bin/sh

# +---------+
# |  Theme  |
# +---------+

# cursor 
yay -S --noconfirm --needed qogir-cursor-theme-git

# font + emojis
sudo pacman -S --needed nerd-fonts
sudo pacman -S --noconfirm --needed noto-fonts-emoji

# icons
sudo pacman -S --noconfirm --needed papirus-icon-theme

# system theme
sudo pacman -S --noconfirm --needed breeze breeze-gtk

# sddm theme
sudo pacman -S --noconfirm --needed gst-libav phonon-qt5-gstreamer gst-plugins-good qt5-quickcontrols qt5-graphicaleffects qt5-multimedia

# +----------+
# |  Config  |
# +----------+

rsync ~/Github/arch/home/.gtkrc-2.0.mine ~/
rsync -r ~/Github/arch/home/config/fontconfig/ ~/.config/fontconfig
rsync -r ~/Github/arch/home/config/gtk-3.0/ ~/.config/gtk-3.0
rsync -r ~/Github/arch/home/config/gtk-4.0/ ~/.config/gtk-4.0
rsync -r ~/Github/arch/home/config/qt5ct/ ~/.config/qt5ct
sudo rsync ~/Github/arch/etc/environment /etc
sudo rsync ~/Github/arch/etc/sddm.conf.d/ /etc/sddm.conf.d
