#!/bin/sh

# ---------- Software Installation ----------

# Steam, Gamemode, Mangohud
sudo pacman -S --needed steam
sudo pacman -S --noconfirm --needed gamemode mangohud

# Discord
sudo pacman -S --noconfirm --needed discord

# Gimp
sudo pacman -S --noconfirm --needed gimp

# Teamspeak
yay -S --noconfirm --needed teamspeak

# MullvadVPN
yay -S mullvad-vpn
